### ISSUE TITLE
Monitoring issue

### ISSUE THREAD

**Issue by 153957** [HiSPARC/station-software#38]
Stations 21, 1101, and 13008 were (re)installed recently.
All seem to have the same monitoring problems:
http://data.hisparc.nl/show/stations/21/status/
http://data.hisparc.nl/show/stations/1101/status/
http://data.hisparc.nl/show/stations/13008/status/

```
Buffer size  - (Service Check Timed Out)
LabviewUsage - CHECK_NRPE: Socket timeout after 30 seconds.
```

These are part of the active checks:
https://github.com/HiSPARC/station-software/blob/master/admin/nsclientpp/active_check.py
which runs this script:
https://github.com/HiSPARC/station-software/blob/master/user/diagnosticchecks/checks.py

**Comment by tomkooij** [comment]
This is due to version admin and user mismatch. 

Problems/changes:
 - `persistent/startstopbatch` and `user/starstop` logic changed.
 - `admin/nsclientpp` changed tot `admin/nsclientcpp/x64'
 - `user/diagnosticchecks/checks.py` has hardcode CONFIG_INI location with relative path (that may be broken)

The problem is a combination of the above.

Solve:
Modify the batchfiles `check_bufferdb.bat` and `check_lvusage.bat` and/or fix CONFIG_INI in `user/diagnosticchecks/check.py` 

run: `%HISPARC_ROOT%\admin\nsclientcpp\???\check_buffdb.bat 0:0 0:0` to test if this is working.
